/* ─── ExportModal ─────────────────────────────────────────────────────────────
   Trip outfit export in 4 formats:
     1. Text itinerary   — .txt download
     2. Visual PNG cards — Canvas-rendered .png download (one combined image)
     3. PDF              — Print-ready HTML in a new window (uses browser print)
     4. Image ZIP        — One PNG per day, sequentially downloaded

   Source of truth: outfitIds (Daily tab data) + wardrobe items.
   Read-only. Never modifies outfit or wardrobe data.
   ─────────────────────────────────────────────────────────────────────────── */

import { useState, useEffect, useMemo } from "react";
import { T, CAT_EMOJI, swatch } from "../theme";
import TRIP from "../data/trip";
import { loadImg, resolveOutfitItems } from "../utils/canvasUtils";

const SLOT_LABELS = {
  daytime:   "Daytime",
  evening:   "Evening",
  breakfast: "Breakfast / Lounge",
  sleepwear: "Sleepwear",
  flight:    "Flight",
  activity:  "Activity",
};
const LAYER_ORDER = ["base", "mid", "outer", "thermalBottom", "bottom", "shoes"];
const LAYER_LABELS = { base: "Top", mid: "Mid", outer: "Outer", thermalBottom: "Thermal", bottom: "Bottom", shoes: "Shoes" };

/* ─── Utility: resolve outfit slot IDs → keyed object { [layer]: item } ─────
   (used by buildExportDays + drawCard; resolveOutfitItems from canvasUtils
    returns an array — this version returns an object keyed by layer name)       */
function resolveSlot(slotIds, wardrobe) {
  if (!slotIds) return null;
  const hasReal = Object.values(slotIds).some((v) => v && v !== "REMOVED");
  if (!hasReal) return null;
  const result = {};
  for (const k of LAYER_ORDER) {
    const id = slotIds[k];
    if (!id || id === "REMOVED") continue;
    const item = wardrobe.find((i) => i.id === id);
    if (item) result[k] = item;
  }
  return Object.keys(result).length > 0 ? result : null;
}

/* ─── Build list of days to export ──────────────────────────────────────── */
export function buildExportDays(outfitIds, frozenDays, wardrobe, frozenOnly) {
  return TRIP
    .filter((day) => {
      const data = outfitIds[day.id];
      if (!data) return false;
      const hasAny = Object.values(data).some((slot) =>
        slot && typeof slot === "object" && Object.values(slot).some((v) => v && v !== "REMOVED")
      );
      if (!hasAny) return false;
      if (frozenOnly && !frozenDays[day.id]) return false;
      return true;
    })
    .map((day) => {
      const data = outfitIds[day.id] || {};
      const slots = {};
      for (const slotKey of Object.keys(SLOT_LABELS)) {
        const resolved = resolveSlot(data[slotKey], wardrobe);
        if (resolved) slots[slotKey] = resolved;
      }
      return { day, slots };
    })
    .filter(({ slots }) => Object.keys(slots).length > 0);
}

/* ─── 1. TEXT EXPORT ─────────────────────────────────────────────────────── */
export function generateText(exportDays) {
  const lines = [
    "AUS & NZ 2026 — TRIP OUTFIT ITINERARY",
    "Generated by SOHIL-WARDROBE",
    "=".repeat(42),
    "",
  ];

  for (const { day, slots } of exportDays) {
    lines.push(`${day.date.toUpperCase()}  ·  ${day.city.toUpperCase()}`);
    lines.push(`Weather: ${day.w}  ·  ${day.occ}`);
    lines.push("");

    for (const [slotKey, items] of Object.entries(slots)) {
      lines.push(`  ${SLOT_LABELS[slotKey].toUpperCase()}`);
      for (const [layer, item] of Object.entries(items)) {
        lines.push(`    ${LAYER_LABELS[layer] || layer}: ${item.n}${item.b ? ` (${item.b})` : ""} — ${item.col}`);
      }
      lines.push("");
    }
    lines.push("-".repeat(42));
    lines.push("");
  }

  return lines.join("\n");
}

function downloadText(exportDays) {
  const text = generateText(exportDays);
  const blob = new Blob([text], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = "trip-outfits.txt";
  a.click();
  URL.revokeObjectURL(url);
}

/* ─── 2. CANVAS PNG EXPORT ───────────────────────────────────────────────── */
const CARD_W  = 380;
const CARD_H  = 500;
const THUMB_W = 80;
const THUMB_H = 80;
const GAP     = 10;
const PAD     = 18;

function drawColorSwatch(ctx, x, y, w, h, color, emoji) {
  const [bg, accent] = swatch(color || "Grey");
  const grad = ctx.createLinearGradient(x, y, x + w, y + h);
  grad.addColorStop(0, bg);
  grad.addColorStop(1, accent);
  ctx.fillStyle = grad;
  ctx.beginPath();
  ctx.roundRect(x, y, w, h, 10);
  ctx.fill();
  // emoji
  ctx.font = `${Math.floor(w * 0.4)}px serif`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(emoji, x + w / 2, y + h / 2);
}

async function drawCard(canvas, dayEntry, previewUrl) {
  const { day, slots } = dayEntry;
  const ctx = canvas.getContext("2d");
  canvas.width  = CARD_W;

  // Calculate height based on number of items across all slots
  let itemCount = 0;
  for (const items of Object.values(slots)) itemCount += Object.keys(items).length;
  const rows   = Math.ceil(itemCount / 4);
  const height = 140 + rows * (THUMB_H + 36) + 40;
  canvas.height = Math.max(CARD_H, height);

  // Pre-load all images in parallel before drawing
  const allItems = Object.values(slots).flatMap((items) => Object.values(items));
  const imgResults = await Promise.all(allItems.map((item) => loadImg(item.img)));
  const imgMap = {};
  allItems.forEach((item, i) => { imgMap[item.id] = imgResults[i]; });
  const previewImg = previewUrl ? await loadImg(previewUrl) : null;

  // Background
  ctx.fillStyle = "#0F0F12";
  ctx.fillRect(0, 0, CARD_W, canvas.height);

  // Header bar
  ctx.fillStyle = "#1A1A1F";
  ctx.beginPath();
  ctx.roundRect(PAD, PAD, CARD_W - PAD * 2, 90, 14);
  ctx.fill();

  // Day emoji + city
  ctx.font = "bold 22px serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText(day.e, PAD + 14, PAD + 12);

  ctx.font = "700 15px 'Cormorant Garamond', Georgia, serif";
  ctx.fillStyle = "#E8E6E1";
  ctx.fillText(day.city.split("→")[0].trim(), PAD + 44, PAD + 12);

  ctx.font = "500 11px DM Sans, sans-serif";
  ctx.fillStyle = "#8A8780";
  ctx.fillText(day.date, PAD + 44, PAD + 32);

  ctx.font = "600 10px DM Sans, sans-serif";
  ctx.fillStyle = "#5C5A55";
  ctx.fillText(`${day.w.toUpperCase()}  ·  ${day.occ.toUpperCase()}`, PAD + 44, PAD + 52);

  if (day.day) {
    ctx.font = "400 10px DM Sans, sans-serif";
    ctx.fillStyle = "#8A8780";
    ctx.fillText(day.day.slice(0, 44), PAD + 14, PAD + 70);
  }

  // If AI preview available, draw it as background strip
  let yOffset = PAD + 104;

  if (previewImg) {
    {
      const ph = 180;
      ctx.save();
      ctx.beginPath();
      ctx.roundRect(PAD, yOffset - 6, CARD_W - PAD * 2, ph, 12);
      ctx.clip();
      ctx.drawImage(previewImg, PAD, yOffset - 6, CARD_W - PAD * 2, ph);
      ctx.restore();
      // gradient overlay
      const overlayGrad = ctx.createLinearGradient(0, yOffset - 6, 0, yOffset - 6 + ph);
      overlayGrad.addColorStop(0, "rgba(15,15,18,0)");
      overlayGrad.addColorStop(1, "rgba(15,15,18,0.7)");
      ctx.fillStyle = overlayGrad;
      ctx.fillRect(PAD, yOffset - 6, CARD_W - PAD * 2, ph);
      yOffset += ph + 8;
    }
  }

  // Outfit items by slot
  for (const [slotKey, items] of Object.entries(slots)) {
    // Slot label
    ctx.font = "700 9px DM Sans, sans-serif";
    ctx.fillStyle = "#5C5A55";
    ctx.textAlign = "left";
    ctx.textBaseline = "top";
    ctx.letterSpacing = "2px";
    ctx.fillText(SLOT_LABELS[slotKey].toUpperCase(), PAD, yOffset);
    yOffset += 16;

    // Items row
    const itemArr = Object.entries(items);
    let xOff = PAD;
    for (const [layer, item] of itemArr) {
      const img = imgMap[item.id];
      if (img) {
        ctx.save();
        ctx.beginPath();
        ctx.roundRect(xOff, yOffset, THUMB_W, THUMB_H, 10);
        ctx.clip();
        ctx.drawImage(img, xOff, yOffset, THUMB_W, THUMB_H);
        ctx.restore();
      } else {
        drawColorSwatch(ctx, xOff, yOffset, THUMB_W, THUMB_H, item.col, CAT_EMOJI[item.c] || "👕");
      }

      // Layer badge
      ctx.font = "700 7px DM Sans, sans-serif";
      ctx.fillStyle = "rgba(232,230,225,0.5)";
      ctx.textAlign = "center";
      ctx.fillText((LAYER_LABELS[layer] || layer).toUpperCase(), xOff + THUMB_W / 2, yOffset + THUMB_H + 4);

      // Item name
      ctx.font = "500 8px DM Sans, sans-serif";
      ctx.fillStyle = "#8A8780";
      const name = item.n.length > 10 ? item.n.slice(0, 9) + "…" : item.n;
      ctx.fillText(name, xOff + THUMB_W / 2, yOffset + THUMB_H + 15);

      xOff += THUMB_W + GAP;
      if (xOff + THUMB_W > CARD_W - PAD) { xOff = PAD; yOffset += THUMB_H + 28; }
    }
    if (xOff > PAD) yOffset += THUMB_H + 28;
    yOffset += 12;
  }

  // Footer watermark
  ctx.font = "600 8px DM Sans, sans-serif";
  ctx.fillStyle = "#26262E";
  ctx.textAlign = "center";
  ctx.fillText("SOHIL-WARDROBE · AUS & NZ 2026", CARD_W / 2, canvas.height - 12);
}

async function downloadVisualPNG(exportDays, previewCache, buildKey) {
  const totalH = exportDays.length * (CARD_H + 16) + 32;
  const master = document.createElement("canvas");
  master.width  = CARD_W + 32;
  master.height = totalH;
  const mCtx = master.getContext("2d");
  mCtx.fillStyle = "#080808";
  mCtx.fillRect(0, 0, master.width, master.height);

  let y = 16;
  // Slot order to check for a hero preview image — daytime first, then others
  const PREVIEW_SLOT_ORDER = ["daytime", "evening", "breakfast", "flight", "activity"];
  for (const entry of exportDays) {
    const card = document.createElement("canvas");
    // Use the first available preview across all slots (not just daytime)
    let previewUrl = null;
    if (buildKey && previewCache) {
      for (const slot of PREVIEW_SLOT_ORDER) {
        const slotItems = entry.slots[slot];
        if (!slotItems) continue;
        const slotIds = Object.fromEntries(
          Object.entries(slotItems).map(([k, item]) => [k, item.id])
        );
        const key = buildKey(entry.day.id, slot, slotIds);
        if (previewCache[key]) { previewUrl = previewCache[key]?.url || previewCache[key]; break; }
      }
    }
    await drawCard(card, entry, previewUrl);
    mCtx.drawImage(card, 16, y);
    y += card.height + 16;
  }

  master.toBlob((blob) => {
    if (!blob) { alert("Export failed: canvas rendering error. Try with fewer days selected."); return; }
    const url = URL.createObjectURL(blob);
    const a   = document.createElement("a");
    a.href     = url;
    a.download = "trip-outfits.png";
    a.click();
    URL.revokeObjectURL(url);
  }, "image/png");
}

/* ─── 3. PDF EXPORT ──────────────────────────────────────────────────────── */
function openPrintWindow(exportDays) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AUS &amp; NZ 2026 — Trip Outfits</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;700&family=DM+Sans:wght@400;500;600;700&display=swap');
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'DM Sans',sans-serif;background:#fff;color:#1a1a1a;padding:32px}
  h1{font-family:'Cormorant Garamond',serif;font-size:26px;font-weight:700;margin-bottom:4px}
  .subtitle{font-size:10px;color:#666;letter-spacing:2px;text-transform:uppercase;margin-bottom:28px}
  .day{page-break-inside:avoid;margin-bottom:28px;border:1.5px solid #e5e5e5;border-radius:12px;overflow:hidden}
  .day-header{background:#f8f8f8;padding:14px 18px;border-bottom:1px solid #e5e5e5}
  .day-emoji{font-size:18px;margin-right:8px}
  .day-city{font-family:'Cormorant Garamond',serif;font-size:17px;font-weight:700}
  .day-date{font-size:10px;color:#888;margin-top:3px}
  .day-meta{font-size:9px;color:#aaa;margin-top:2px;letter-spacing:1px;text-transform:uppercase}
  .slots{padding:12px 18px}
  .slot{margin-bottom:12px}
  .slot-label{font-size:9px;font-weight:700;color:#888;letter-spacing:2px;text-transform:uppercase;margin-bottom:6px}
  .items{display:flex;flex-wrap:wrap;gap:6px}
  .item{background:#f5f5f5;border-radius:8px;padding:6px 10px;font-size:10px}
  .item-name{font-weight:600;color:#333}
  .item-detail{color:#888;margin-top:1px}
  @media print{body{padding:16px}.day{page-break-inside:avoid}}
</style>
</head>
<body>
<h1>AUS &amp; NZ 2026</h1>
<p class="subtitle">Trip Outfit Guide · ${exportDays.length} Days</p>
${exportDays.map(({ day, slots }) => `
<div class="day">
  <div class="day-header">
    <div>
      <span class="day-emoji">${day.e}</span>
      <span class="day-city">${day.city}</span>
    </div>
    <div class="day-date">${day.date}</div>
    <div class="day-meta">${day.w} · ${day.occ}${day.day ? ` · ${day.day}` : ""}</div>
  </div>
  <div class="slots">
    ${Object.entries(slots).map(([slotKey, items]) => `
    <div class="slot">
      <div class="slot-label">${SLOT_LABELS[slotKey]}</div>
      <div class="items">
        ${Object.entries(items).map(([layer, item]) => `
        <div class="item">
          <div class="item-name">${item.n}</div>
          <div class="item-detail">${LAYER_LABELS[layer] || layer} · ${item.col}${item.b ? ` · ${item.b}` : ""}</div>
        </div>`).join("")}
      </div>
    </div>`).join("")}
  </div>
</div>`).join("")}
<script>window.onload=()=>window.print()</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) { alert("Allow pop-ups to open the print/PDF view."); return; }
  win.document.write(html);
  win.document.close();
}

/* ─── 4. ZIP (sequential PNG downloads) ─────────────────────────────────── */
async function downloadZip(exportDays, previewCache, buildKey, setProgress) {
  for (let i = 0; i < exportDays.length; i++) {
    const entry = exportDays[i];
    setProgress(Math.round(((i + 1) / exportDays.length) * 100));
    const card = document.createElement("canvas");
    const previewKey = null; // skip preview for zip to keep it fast
    await drawCard(card, entry, previewKey);
    await new Promise((resolve) => {
      card.toBlob((blob) => {
        const url = URL.createObjectURL(blob);
        const a   = document.createElement("a");
        a.href     = url;
        a.download = `outfit-${entry.day.id}-${entry.day.date.replace(/\s/g, "-")}.png`;
        a.click();
        setTimeout(() => { URL.revokeObjectURL(url); resolve(); }, 300);
      }, "image/png");
    });
  }
  setProgress(null);
}

/* ─── Day Preview Card (modal scroll list) ───────────────────────────────── */
function DayPreviewCard({ dayEntry }) {
  const { day, slots } = dayEntry;
  return (
    <div style={{
      background: T.alt, borderRadius: 12,
      border: `1px solid ${T.borderLight}`,
      padding: "12px 14px", marginBottom: 8,
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 6 }}>
        <span style={{ fontSize: 16 }}>{day.e}</span>
        <div>
          <span style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 13, fontWeight: 700, color: T.text }}>
            {day.city.split("→")[0].trim()}
          </span>
          <span style={{ fontSize: 9, color: T.light, marginLeft: 6 }}>{day.date}</span>
        </div>
      </div>
      {Object.entries(slots).map(([slotKey, items]) => (
        <div key={slotKey} style={{ marginBottom: 4 }}>
          <span style={{ fontSize: 8, fontWeight: 700, color: T.light, letterSpacing: 1.2 }}>
            {SLOT_LABELS[slotKey].toUpperCase()}
          </span>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 4, marginTop: 3 }}>
            {Object.entries(items).map(([layer, item]) => (
              <span key={layer} style={{
                fontSize: 9, background: T.surface, border: `1px solid ${T.borderLight}`,
                borderRadius: 6, padding: "2px 7px", color: T.mid,
              }}>
                {item.n}
              </span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

/* ─── EXPORT MODAL ───────────────────────────────────────────────────────── */
export default function ExportModal({
  outfitIds,
  frozenDays,
  wardrobe,
  previewCache,     // { [key]: imageUrl } from usePreview cache state
  buildPreviewKey,  // (dayId, slot, slotIds) => string
  onClose,
}) {
  const [frozenOnly, setFrozenOnly] = useState(true);
  const [busy,       setBusy]       = useState(false);
  const [progress,   setProgress]   = useState(null); // 0-100 for zip
  const [done,       setDone]       = useState(null);  // format label

  // Close on Escape
  useEffect(() => {
    const fn = (e) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", fn);
    return () => window.removeEventListener("keydown", fn);
  }, [onClose]);

  const exportDays = useMemo(
    () => buildExportDays(outfitIds, frozenDays, wardrobe, frozenOnly),
    [outfitIds, frozenDays, wardrobe, frozenOnly]
  );

  const frozenCount  = TRIP.filter((d) => frozenDays[d.id]).length;
  const plannedCount = TRIP.filter((d) => {
    const data = outfitIds[d.id];
    return data && Object.values(data).some((s) => s && typeof s === "object" &&
      Object.values(s).some((v) => v && v !== "REMOVED"));
  }).length;

  async function run(label, fn) {
    setBusy(true);
    setDone(null);
    try {
      await fn();
      setDone(label);
      setTimeout(() => setDone(null), 3000);
    } catch (err) {
      console.error("Export error:", err);
      alert(`Export failed: ${err.message}`);
    } finally {
      setBusy(false);
    }
  }

  const BtnStyle = (accent) => ({
    width: "100%",
    padding: "13px 16px",
    borderRadius: 12,
    border: `1.5px solid ${busy ? T.borderLight : accent}`,
    background: busy ? T.alt : "none",
    color: busy ? T.light : accent,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    cursor: busy ? "not-allowed" : "pointer",
    fontFamily: "inherit",
    display: "flex",
    alignItems: "center",
    gap: 10,
    transition: "all 0.15s",
    textAlign: "left",
  });

  return (
    <div
      style={{
        position: "fixed", inset: 0, background: "rgba(0,0,0,0.9)",
        zIndex: 1100, display: "flex", alignItems: "flex-end", justifyContent: "center",
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: T.surface,
          borderRadius: "22px 22px 0 0",
          width: "100%", maxWidth: 520,
          maxHeight: "92vh", overflowY: "auto",
          animation: "slideUp 0.22s ease-out",
          paddingBottom: 32,
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* ── Header ── */}
        <div style={{
          display: "flex", justifyContent: "space-between", alignItems: "center",
          padding: "18px 20px 14px",
          borderBottom: `1px solid ${T.borderLight}`,
          position: "sticky", top: 0, background: T.surface, zIndex: 1,
        }}>
          <div>
            <span style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 18, fontWeight: 700, color: T.text }}>
              Export Outfits
            </span>
            <p style={{ fontSize: 10, color: T.light, marginTop: 3 }}>
              AUS &amp; NZ 2026 · {exportDays.length} day{exportDays.length !== 1 ? "s" : ""} selected
            </p>
          </div>
          <button onClick={onClose} style={{
            background: "none", border: `1.5px solid ${T.border}`,
            borderRadius: "50%", width: 30, height: 30,
            display: "flex", alignItems: "center", justifyContent: "center",
            color: T.mid, fontSize: 14, cursor: "pointer",
          }}>✕</button>
        </div>

        <div style={{ padding: "16px 20px" }}>

          {/* ── Scope selector ── */}
          <div style={{
            display: "flex", gap: 6, marginBottom: 16,
            background: T.alt, borderRadius: 10, padding: 4,
          }}>
            {[
              { label: `🔒 Frozen (${frozenCount})`, frozen: true },
              { label: `◫ All Planned (${plannedCount})`, frozen: false },
            ].map(({ label, frozen }) => (
              <button
                key={String(frozen)}
                onClick={() => setFrozenOnly(frozen)}
                style={{
                  flex: 1, padding: "8px", borderRadius: 7,
                  background: frozenOnly === frozen ? T.surface : "none",
                  border: `1px solid ${frozenOnly === frozen ? T.border : "transparent"}`,
                  color: frozenOnly === frozen ? T.text : T.light,
                  fontSize: 11, fontWeight: frozenOnly === frozen ? 700 : 500,
                  cursor: "pointer", fontFamily: "inherit",
                  transition: "all 0.15s",
                }}
              >
                {label}
              </button>
            ))}
          </div>

          {/* ── Preview list ── */}
          {exportDays.length === 0 ? (
            <div style={{
              padding: "32px", textAlign: "center",
              color: T.light, fontSize: 12,
              border: `1.5px dashed ${T.borderLight}`, borderRadius: 12, marginBottom: 16,
            }}>
              {frozenOnly ? "No frozen days with outfits yet." : "No planned days with outfits yet."}
            </div>
          ) : (
            <div style={{ maxHeight: 240, overflowY: "auto", marginBottom: 16 }}>
              {exportDays.map((entry) => (
                <DayPreviewCard key={entry.day.id} dayEntry={entry} />
              ))}
            </div>
          )}

          {/* ── Export format buttons ── */}
          {exportDays.length > 0 && (
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              {/* 1. Text */}
              <button
                disabled={busy}
                onClick={() => run("Text", () => downloadText(exportDays))}
                style={BtnStyle("#4ADE80")}
              >
                <span style={{ fontSize: 18 }}>📄</span>
                <div>
                  <div>Text Itinerary</div>
                  <div style={{ fontSize: 9, fontWeight: 400, opacity: 0.7 }}>Download .txt with all outfits per day</div>
                </div>
                {done === "Text" && <span style={{ marginLeft: "auto", fontSize: 12 }}>✓</span>}
              </button>

              {/* 2. Visual PNG */}
              <button
                disabled={busy}
                onClick={() => run("Visual", () => downloadVisualPNG(exportDays, previewCache, buildPreviewKey))}
                style={BtnStyle("#93C5FD")}
              >
                <span style={{ fontSize: 18 }}>🖼</span>
                <div>
                  <div>Visual Outfit Cards</div>
                  <div style={{ fontSize: 9, fontWeight: 400, opacity: 0.7 }}>Download combined PNG with all outfit cards</div>
                </div>
                {busy && done !== "Visual" && <span style={{ marginLeft: "auto", fontSize: 11 }}>rendering…</span>}
                {done === "Visual" && <span style={{ marginLeft: "auto", fontSize: 12 }}>✓</span>}
              </button>

              {/* 3. PDF */}
              <button
                disabled={busy}
                onClick={() => run("PDF", () => openPrintWindow(exportDays))}
                style={BtnStyle("#F9A8D4")}
              >
                <span style={{ fontSize: 18 }}>📋</span>
                <div>
                  <div>PDF Guide</div>
                  <div style={{ fontSize: 9, fontWeight: 400, opacity: 0.7 }}>Open print-ready page → Save as PDF</div>
                </div>
                {done === "PDF" && <span style={{ marginLeft: "auto", fontSize: 12 }}>✓</span>}
              </button>

              {/* 4. ZIP */}
              <button
                disabled={busy}
                onClick={() => run("ZIP", () =>
                  downloadZip(exportDays, previewCache, buildPreviewKey, setProgress)
                )}
                style={BtnStyle("#FBBF24")}
              >
                <span style={{ fontSize: 18 }}>📦</span>
                <div>
                  <div>Download All (PNG per day)</div>
                  <div style={{ fontSize: 9, fontWeight: 400, opacity: 0.7 }}>
                    {progress !== null
                      ? `Downloading ${progress}%…`
                      : "One PNG file per day, downloaded sequentially"}
                  </div>
                </div>
                {done === "ZIP" && <span style={{ marginLeft: "auto", fontSize: 12 }}>✓</span>}
              </button>
            </div>
          )}

          {/* Progress bar */}
          {progress !== null && (
            <div style={{ marginTop: 10, height: 3, background: T.alt, borderRadius: 2, overflow: "hidden" }}>
              <div style={{
                height: "100%", width: `${progress}%`,
                background: "#FBBF24", transition: "width 0.3s",
              }} />
            </div>
          )}

          <p style={{ fontSize: 9, color: T.light, textAlign: "center", marginTop: 14, lineHeight: 1.5 }}>
            Export is read-only · Outfit data is never modified
          </p>
        </div>
      </div>
    </div>
  );
}
